version: '3.7'
volumes:
    traefik:
services:
    voting-api:
        build: ./voting-backend
        ports:
            - '4000:4000'
        links:
            - mongo
        depends_on:
            - mongo
        container_name: voting-api
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.voting-api.rule=Host(`${API_DOMAIN}`)'
            - 'traefik.http.routers.voting-api.entrypoints=web, websecure'
            - 'traefik.http.routers.voting-api.tls.certresolver=myresolver'

    voting-web:
        build:
            context: ./voting-client
            dockerfile: Dockerfile
            args:
                REACT_APP_API_URL: ${REACT_APP_API_URL}
        ports:
            - '81:80'
        depends_on:
            - voting-api
        links:
            - voting-api
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.voting-web.rule=Host(`${CLIENT_DOMAIN}`)'
            - 'traefik.http.routers.voting-web.entrypoints=web, websecure'
            - 'traefik.http.routers.voting-web.tls.certresolver=myresolver'
